spring.application.name=ProjectImpl_Kilic_FerideCeren_s27614

spring.datasource.url=jdbc:h2:mem:masdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.security.user.password=1234spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

